# Site settings
name: 'Allison Liu'
description: 'allisonznliu@gmail.com'
meta_description: ''
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'bio-photo1.jpg'
  greetings: "Hi! My name is Allison Liu. I'm passionate about improving sustainability through about uncovering and understanding patterns in data."
favicon: 'assets/images/favicon.ico'
baseurl:
production_url: https://allisonznliu.com/
# Add your GA Tracking Id
ga_analytics: G-1HG83XG8WR

# Social links
github: 'a11isonliu'
linkedin: 'allison-liu-685497159'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Projects
    url: /projects
  - text: Publications
    url: /publications


# Required Plugins
plugins_dir:
  # - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  # - jekyll-tagsgenerator

collections:
  tags:
    output: true
    order: 
      - machinelearning.md
      - appm.md
      - algorithms.md
      - engineering.md
      - sciencewriting.md
      - climbing.md

# Pagination
# paginate: 10
# paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

